spark.master                     spark://spark-master:7077
spark.serializer                 org.apache.spark.serializer.KryoSerializer
spark.sql.session.timeZone       UTC
spark.sql.shuffle.partitions     8
spark.ui.showConsoleProgress     true
spark.driver.memory              1g
spark.executor.memory            768m
spark.executor.cores             2
